language: node_js

node_js:
  - 6
  - 7

cache:
  yarn: true
  directories:
    - node_modules
    - packages/eslint-config-honeycomb/node_modules
    - packages/honeycomb-assets/node_modules
    - packages/honeycomb-health-middleware/node_modules
    - packages/honeycomb-info-middleware/node_modules
    - packages/honeycomb-layout/node_modules
    - packages/honeycomb-logging-middleware/node_modules
    - packages/honeycomb-registry-client/node_modules
    - packages/generator-honeycomb/node_modules

after_success:
  - './node_modules/.bin/istanbul report --dir ./coverage --include **/coverage/*.json lcov'
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
