language: node_js
node_js:
  - 6.4.0
  - stable
cache:
  directories:
    - node_modules
env:
  - TEST_DIR=honeycomb-registry-client
  - TEST_DIR=honeycomb-template
before_install:
  - |
    if [ "$TEST_DIR" = honeycomb-template ]; then
      # Linking local npm modules via npm-workspace
      npm install
    fi
  - cd $TEST_DIR
before_script:
  - |
    if [ "$TEST_DIR" = honeycomb-template ]; then
      # Integration test
      npm run build
      npm run start:production
    fi
