language: node_js
cache:
  directories:
    - node_modules
    - packages/honeycomb-layout/node_modules
    - packages/honeycomb-registry-client/node_modules
    - packages/generator-honeycomb/node_modules
