version: '2'

services:
  example-handlebars:
    build: ./packages/example-handlebars
    ports:
      - "3001:3000"

  example-react:
    build: ./packages/example-react
    ports:
      - "3002:3000"

  layout:
    build: ./packages/honeycomb-layout
    ports:
      - "3000:3000"
    links:
      - example-react
      - example-handlebars
